feat!: Remove high-io Postgres plans
No applications are currently using these plans.

They provision an RDS instance with a large number of IOPS which can
cause the costs associated with that RDS instance to jump
substantially. In the region of several thousands of dollars per
month.

For teams that want to provision a high IO instance they can do so
by manually specifing the attributes "iops" and "storage_type".

It is recommended that instead of using a "high-io" plan with a
fixed iops value, that some research is performed between the
service team and platform team into what an appropriate value
would be for their specific application and then specify that
exact figure.

For any teams that try to use these plans in future they'll
now see a validation error when generating environment tf:

> Error: Schema error in platform-config.yml. Key 'extensions' error:
> Key 'demodjango-postgres' error:

Signed-off-by: DBT pre-commit check