fix: Permit enironment-pipeline to create role:AWSServiceRoleForElasticache (off-ticket) (#1334)
This role is needed by the environment-pipeline to create new Redis cache instances.

If the role has already been created (once per AWS Account) then the pipelines won't error.

If a Redis cache has never been created in an AWS Account, but an application team tries to create one using the environment pipeline then they get the following error from Terraform apply:

```
Error: creating ElastiCache Subnet Group ...
api error ServiceLinkedRoleNotFoundFault: This action cannot be completed due to insufficient permissions.
(Recommended action) Please create new role using IAM API CreateServiceLinkedRole.
```

IAM Permissions taken from https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/using-service-linked-roles.html#service-linked-role-permissions

This defect was identified as part of ZenDesk support ticket 198532

Signed-off-by: DBT pre-commit check