fix: Accept deploy remote URL without .git suffix (off-ticket) (#1197)
Fixes an issue identified during a support ticket where a deploy
repo which has been cloned like so...

  $ git clone git@github.com:uktrade/demodjango-deploy

When running `platform-helper generate` it gives the following
error...

  $ AWS_PROFILE=platform-sandbox platform-helper generate
  15.15.0
  Error: 'NoneType' object has no attribute 'group'

Adds test for this format of remote URL and adjusts the regex
to make .git optional